# Generated by Django 3.2.9 on 2021-11-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='media/image')),
            ],
            options={
                'verbose_name_plural': 'Sep',
            },
        ),
        migrations.CreateModel(
            name='Student_Life',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='media/image')),
                ('deck', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Student_Life',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='media/image')),
                ('deck', models.TextField()),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Subject',
            },
        ),
    ]
